name: CI/CD Teste DevOps

on:
  push:
    branches:
      - main
      - develop
      - homolog

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Validar arquivos do site
        run: ls -R

  sonar:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          args: >
            -Dsonar.projectKey=Teste-Devops
            -Dsonar.organization=itsleocamargo
            -Dsonar.sources=.
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  deploy:
    runs-on: ubuntu-latest
    needs: sonar
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Deploy para Azure Storage
        uses: azure/storage-blob-upload-action@v1
        with:
          connection-string: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
          container-name: '$web'
          source: '.'
