name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

  sonarcloud:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: SonarCloud Scan
        uses: sonarsource/sonarqube-scan-action@v5
        with:
          projectKey: Teste-Devops
          organization: itsleocamargo
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  deploy:
    runs-on: ubuntu-latest
    needs: sonarcloud
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Deploy para Azure Storage
        uses: azure/storage-blob-upload-action@v1
        with:
          connection-string: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
          container-name: '$web'
          source: '.'
